version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade --user awscli
      - npm install
      - chmod +x ./build/read-environment.sh
      - npm run build
  build:
    commands:
      - export Bucket=`aws cloudformation list-exports --output text --query "Exports[?(Name=='basiq-blink-s3-bucket')].Value"`
      - aws s3 sync dist s3://$Bucket/v1 --acl public-read
